### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by PaoloKa** [paulocoutinhox/pdfium-lib#103]
**Describe the bug**

Depot tools now requires python 3.8

![image](https://github.com/paulocoutinhox/pdfium-lib/assets/30302837/556fa940-e174-438d-8e0d-e3c91d8299ab)

**To Reproduce**

1. Run pipeline
2. Error will happen within the build step (see image)

![image](https://github.com/paulocoutinhox/pdfium-lib/assets/30302837/5e440827-9a11-4c78-ac03-fe5ac9d9d2ef)

**Expected behavior**

Building with the new version of depot tools should be working

**Comment by paulocoutinhox** [comment]
Hi,

I have updated everything.

You can now use the latest version.

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

Project was updated to latest version.

If your problem was solved, can you close the issue pls?

Thanks.
