### ISSUE TITLE
Failed to link to libpdfium.so

### ISSUE THREAD

**Issue by UEPSs** [paulocoutinhox/pdfium-lib#112]
**Describe the bug**
I downloaded [v6276](https://github.com/paulocoutinhox/pdfium-lib/releases/tag/6276) prebuilt binary for android from release page.
When I used it in my android JNI project and built, I get lots of errors:

> ld: error: undefined symbol: FPDF_CloseDocument
> ld: error: undefined symbol: FPDF_DestroyLibrary
> ld: error: undefined symbol: FPDF_LoadCustomDocument
> ...

It seems there're something wrong with this libpdfium.so file.
I listed all symbols in this so file by "nm -gD libpdfium.so" and found no symbols like FPDF_CloseDocument, FPDF_DestroyLibrary ... ,which confirmed the problem.

**To Reproduce**

1. Execute on terminal 'nm -gD libpdfium.so'
2. Find symbol like FPDF_CloseDocument in output

**Expected behavior**
There should be symbols like FPDF_CloseDocument.

**Screenshots**
![image](https://github.com/paulocoutinhox/pdfium-lib/assets/78903256/286173d0-3beb-46e8-8640-740a1d416f5f)

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04
 - Target android

**Comment by buehler** [comment]
Experiencing the same error. Just did some digging. in V6008, the libs (as well as other required libs) are still in the zip and the pdfium lib contains the required symbols. After that version, all other libs (c++ and whatever) as well as the symbols are absent.

**Comment by paulocoutinhox** [comment]
Hi,

Project was updated to latest version.

If your problem was solved, can you close the issue pls?

Thanks.

**Comment by UEPSs** [comment]
@paulocoutinhox The problem still exists

**Comment by paulocoutinhox** [comment]
Can you share a simple project to me that use it?

I will put in sample-android to auto test.

**Comment by UEPSs** [comment]
@paulocoutinhox You can use this project [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid), my project is based on it.

**Comment by paulocoutinhox** [comment]
Hi @UEPSs,

You can download the latest version, it was fixed.

If it solve to you, close this issue pls.

Thanks.
