### ISSUE TITLE
[Question] May I have typescript definition file for pdfium

### ISSUE THREAD

**Issue by tianmuji** [paulocoutinhox/pdfium-lib#115]
I am trying to integrate pdfium via webassembly
so I am trying to find type declaration file for the pdfium api
Otherwise I will do that myself

**Comment by paulocoutinhox** [comment]
Hi,

We don't have it, but will be nice if you can contribute and add it.

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

Project was updated to latest version.

If your problem was solved, can you close the issue pls?

Thanks.
