### ISSUE TITLE
【Question】is FPDFTextObj_Delete method exported?

### ISSUE THREAD

**Issue by tianmuji** [paulocoutinhox/pdfium-lib#117]
I check the source code and surprisingly there is no FPDFTextObj_Delete

but according to the doc in https://cdn01.foxitsoftware.com/pub/foxit/manual/enu/FoxitPDF_SDK20_Guide.pdf
there is function called FPDFTextObj_Delete in text edit module

Could you please help me figure out this problem

**Comment by paulocoutinhox** [comment]
This function don't exists in source code:
https://github.com/search?q=repo%3Achromium%2Fpdfium%20FPDFTextObj_Delete&type=code

But other don't exists too:
- FPDFTextObj_Find
- FPDFTextObj_Delete
etc

On google you don't have it too:
https://www.google.com/search?q=%22FPDFTextObj_Delete%22&sca_esv=88d037c54ddcbe29&sxsrf=ADLYWIKQMenE6eVW7ZZ4uJlyjOx9IWZujQ%3A1720803061701&ei=9V6RZo6_KsuC5OUP1N6E4AE&ved=0ahUKEwjOjeL5-qGHAxVLAbkGHVQvARwQ4dUDCA8&uact=5&oq=%22FPDFTextObj_Delete%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiFCJGUERGVGV4dE9ial9EZWxldGUiMggQABiABBiiBDIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBEjeD1DQBVjcDHABeAGQAQCYAZ8BoAGfAqoBAzAuMrgBA8gBAPgBAZgCA6ACrALCAgoQABiwAxjWBBhHmAMA4gMFEgExIECIBgGQBgOSBwMxLjKgB4sH&sclient=gws-wiz-serp

**Comment by paulocoutinhox** [comment]
Did you find what you need?

**Comment by tianmuji** [comment]
> Did you find what you need?

No, pdfium does not guarantee to provide same api as foxit

I am trying to get TextObj to achieve text editing
my approach is to get all objects from page.
then iterate all objects
if object type is text, then get all values from it, by using canvas, I can make editing effect
after editing, I will update changes back to the file

but in pdfium fpdf_edit.h, there is no api for this functionality.

so it seems to be impossible to achieve text editing using pdfium(I think this is really wired, because I guess there should be some projects have used pdfium to do this, maybe in Android they do

only if someone can help with this or pdfium support more api,  there will be hope to edit text.
