### ISSUE TITLE
build a specific version of pdfium

### ISSUE THREAD

**Issue by xudesheng** [paulocoutinhox/pdfium-lib#126]
**Is your feature request related to a problem? Please describe.**
I'm using `pdfium-render` in my Rust program; it has a dependency on the binary library from `https://github.com/bblanchon/pdfium-binaries.`

However, `https://github.com/bblanchon/pdfium-binaries` only provides few version of library for dynamic link only.  The current available versions are: pdfium_6611, pdfium_6569, pdfium_6555, pdfium_6490, pdfium_6406, pdfium_6337, pdfium_6295, pdfium_6259, pdfium_6164, pdfium_6124, pdfium_6110, pdfium_6084, pdfium_6043, pdfium_6015, pdfium_5961.

I want to use your tool to build a specific version since the outcome can support static links, such as `PDFium 128.0.6611.0`. Then, I can use `pdfium-render` with a static link.

**Describe the solution you'd like**
Could you consider to add an optional argument in command line to pull out specific version from `https://pdfium.googlesource.com/pdfium`?

**Describe alternatives you've considered**

**Additional context**

**Comment by xudesheng** [comment]
ok, I found it's already in the config. thanks.

**Comment by paulocoutinhox** [comment]
Hi,

It is in the config file, but if you use docker, you need change there (find and replace is better).

Im making a new version with some fixes, maybe some hours it is finished.

Thanks.
