### ISSUE TITLE
Huge size increase since 6662

### ISSUE THREAD

**Issue by kernoeb** [paulocoutinhox/pdfium-lib#135]
In [6658](https://github.com/paulocoutinhox/pdfium-lib/releases/tag/6658), the `libpdfium.a` size for macOS was ~25Mb.

Now, the last `libpdfium.a` is 294Mb 🤔 

Is it intended or does a configuration changed somewhere during the build process ?

Thanks !

**Comment by paulocoutinhox** [comment]
Sorry. It was fixed here:
https://github.com/paulocoutinhox/pdfium-lib/releases/tag/6694

After CI finish build, it will be available there.

**Comment by kernoeb** [comment]
No worries, thanks for your responsiveness!
