### ISSUE TITLE
Example for FPDF_RenderPageBitmapWithMatrix method

### ISSUE THREAD

**Issue by nguyenyou** [paulocoutinhox/pdfium-lib#142]
Hi,
I’m currently working on rendering a PDF page into multiple smaller images to improve rendering performance, instead of rendering the entire page at once. I’ve tried using the FPDF_RenderPageBitmap method, but it doesn’t seem to have the functionality I need.

Could anyone provide an example of how to use the FPDF_RenderPageBitmapWithMatrix method? Alternatively, any guidance or resources on implementing this would be greatly appreciated.

Thank you!

**Comment by paulocoutinhox** [comment]
Hi,

You can use the render method passing a lower scale value:

<img width="434" alt="image" src="https://github.com/user-attachments/assets/db2de1df-d696-4551-beae-2afa697468d6">

https://github.com/paulocoutinhox/pdfium-lib/blob/master/extras/wasm/template/index.html#L189

The current value is 3.0:

https://github.com/paulocoutinhox/pdfium-lib/blob/master/extras/wasm/template/index.html#L105

**Comment by nguyenyou** [comment]
Hi @paulocoutinhox,

Thank you for your quick response. Reducing the scale helps, and I’m already using a low scale to render placeholders for PDF pages while, at the same time, rendering the PDF pages in high quality to improve the user experience during the wait.

However, when I look at the nutrient PDF viewer, I see that they split the page into many smaller images and continuously deliver them to the user, which I believe is a better approach. Do you have any ideas on how to split the page into many smaller images? It seems similar to the image cropping feature.

https://www.nutrient.io/demo/viewer
<img width="2049" alt="Screenshot 2024-11-19 at 09 17 12" src="https://github.com/user-attachments/assets/09b39811-19cd-46e6-8e4b-05ba985d30f9">

**Comment by nguyenyou** [comment]
Hi @paulocoutinhox , 
I finally figured out how to do it, I'll closed this issue.

**Comment by nguyenyou** [comment]
By the way, this is called https://en.wikipedia.org/wiki/Tiled_rendering
