### ISSUE TITLE
Bitmaps larger than 495 × 495 × 4 leak in WASM

### ISSUE THREAD

**Issue by CetinSert** [paulocoutinhox/pdfium-lib#33]
**Describe the bug**
`FPDF.Bitmap_Destroy()` leaks above a certain size in multiple browsers.

**To Reproduce**

1. Go to https://pdfviewer.github.io/
2. Open developer tools
3. Add 2 live expressions to watch: `wasmMemory` and `wasmMemory.buffer.byteLength` (only in Chrome-like browsers)
![image](https://user-images.githubusercontent.com/27027/121821720-b1526700-ccd5-11eb-833c-59e16091bb0e.png)

5. You can also open the browser task manager with: <kbd>Shift</kbd> + <kbd>Esc</kbd>, locate the PDF Viewer tab there and watch that
6. Evaluate the following one block at a time in the developer console (reload tab in between each block for test hygiene)

---

(`_PDFium_Init()` is repeated for your copy+paste convenience and repeating/not-repeating it does not change the behavior.)

### 1. `s` `=` `1000`; `_free(_malloc(())` – evaluate in console ✔️ (no leak)
```js
wasmMemory
wasmMemory.buffer.byteLength
```
```js
_PDFium_Init(); var s = 1000; for (let i = 0; i < 100; i++) _free(_malloc(s * s * 4)); // ✔️
```
```js
wasmMemory.buffer.byteLength
wasmMemory
```

### 2. `s` `=` `100`; `Destroy(CreateEx(s, s, 4)` ✔️
```js
_PDFium_Init(); var s = 100; for (let i = 0; i < 10; i++) FPDF.Bitmap_Destroy(FPDF.Bitmap_CreateEx(s, s, 4)); // ✔️
```

### 3. `s` `=` `495` ✔️
```js
_PDFium_Init(); var s = 495; for (let i = 0; i < 10; i++) FPDF.Bitmap_Destroy(FPDF.Bitmap_CreateEx(s, s, 4)); // ✔️
```

### 4. `s` `>=` `496` ❌
```js
_PDFium_Init(); var s = 496; for (let i = 0; i < 10; i++) FPDF.Bitmap_Destroy(FPDF.Bitmap_CreateEx(s, s, 4)); // ❌
```

---

Bindings to confirm bitmap behavior.

```js
_PDFium_Init();
FPDF.Bitmap_GetWidth  = Module.cwrap('FPDFBitmap_GetWidth',  'number', ['number']);
FPDF.Bitmap_GetHeight = Module.cwrap('FPDFBitmap_GetHeight', 'number', ['number']);
FPDF.Bitmap_GetBuffer = Module.cwrap('FPDFBitmap_GetBuffer', 'number', ['number']);
FPDF.Bitmap_Create    = Module.cwrap('FPDFBitmap_Create',    'number', ['number', 'number', 'number']); // ⚠️ same issue
```

---

**Expected behavior**
There should be no leaks at any size.

**System (please complete the following information):**
 - OS: Windows 10 Version `20H2` (OS Build `19042.1055`)
 - Browsers: Chrome `91.0.4472.77`; Firefox `89.0`

**Comment by cetinsert** [comment]
The above holds true even if we tell `FPDF` to use an external buffer as in `FPDF.Bitmap_CreateEx(width, height, format, buffer, ⋯)`.

**Comment by cetinsert** [comment]
@paulo-coutinho Can you please test this in `C++`? Should the issue persist there, we can forward this issue to Google.

**Comment by cetinsert** [comment]
References
https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4505/fpdfsdk/fpdf_view.cpp#884 calls into `retain_ptr.h`
https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4505/core/fxcrt/retain_ptr.h
https://pdfium.googlesource.com/pdfium/+/refs/heads/master/core/fxcrt/retain_ptr.h (same as above)

**Comment by cetinsert** [comment]
Calling it with pauses between each call exhibits the same leak:
### `s` `=` `495` ✔️
![image](https://user-images.githubusercontent.com/27027/121823905-2d06e080-cce3-11eb-87d1-3aa309b62080.png)
### `s` `=` `496` ❌
![image](https://user-images.githubusercontent.com/27027/121823862-dbf6ec80-cce2-11eb-9264-23c99676c6d3.png)

**Comment by paulo-coutinho** [comment]
I have updated all to latest version:
https://pdfviewer.github.io/

Can you check?

**Comment by paulo-coutinho** [comment]
The last version updated is here:
https://github.com/paulo-coutinho/pdfium-lib/releases/tag/4542

**Comment by cetinsert** [comment]
I have just checked. The issue persists and is as suspected to come from upstream.
![image](https://user-images.githubusercontent.com/27027/121970572-cac8e100-cdb1-11eb-9240-1050da4b62ed.png)

**Comment by cetinsert** [comment]
I tried contacting the project by email according to https://groups.google.com/g/pdfium-bugs/about but was rejected as a non-Google-r.

There is another person who did mention a leak with a similar code path https://groups.google.com/g/pdfium-bugs/c/KO4Id_s4w-c/m/wqE9u_EuDQAJ although the conversation eventually fails to converge on `Bitmap_Destroy` and `Bitmap_Create*` and looks at other calls.

I suspect such leaks might be acceptable in the context PDFium is used in a browser: A user opening a single PDF document is in its own web-isolated tab to view it for a short period of time. Bringing the project to web proper via WASM though opens up lots of many-file, long-lived, highly-interactive use cases that are intolerant of any leaks.

**Comment by cetinsert** [comment]
I see following options remaining.

1. check and address the issue outside WASM, in C/C++ (⭐⭐⭐⭐⭐)
    1. confirm it exists (@paulo-coutinho, can you help with this part? If not I will get started sometime within this week.)
    2. debug it there
    3. fix it
    4. create patch for at least your repository
2. find a way to contact PDFium at google to let them know of the issue (⭐⭐ – must be done but will probably be ignored / take too long for an actual change)
3. check Foxit's similar project sources F in FPDF stands for Foxit (the company Google licensed it from) (⭐⭐ –  lots of searching)
4. render in 495 × 495 × 4 fragments and stich the page together o__O (⭐/⭐⭐⭐⭐ – not sure if the APIs are really there but even if they are, can still have lots of issues with performance if single-threaded, visible seams at the boundaries, code complexity, etc.; if very carefully done and multi-threaded it might turn out to be faster than non-fragmented renders though (assuming seams are not an issue with their API))
5. kill and restart the PDFium WASM runtime transparently on the first out of memory failure (⭐)
6. use one web worker + PDFium WASM instance per loaded PDF file (this is how PDF.js works too – every loaded document, generates its own web worker / thread in the background until that document is closed); I was only using one web worker for all PDF files (⭐⭐ – there are likely other leaks (a few were even mentioned in their google group) and memory usage will eventually grow to huge sizes (pushing mobile devices out of reach for any real use); currently `wasmMemory.buffer.byteLength` starts at 16M which is acceptable even when repeated for each PDF file but I have not checked the other parts of the code path we follow to get page images in browsers; these might be memory-heavy and worse also leaky at other places)
7. find a way to render pages avoiding the leaky `Bitmap_Destroy` and `Bitmap_Create*` functions (⭐⭐⭐⭐⭐ – but there might be none)

---

5 and 6 combined: (⭐⭐⭐)

**Comment by cetinsert** [comment]
I posted to https://groups.google.com/g/pdfium instead but my post is pending approval.

```
Bitmaps larger than 495 × 495 × 4 leak with Bitmap_Destroy(Bitmap_Create*()))
```

```
This is being tracked here with a single-line test case: https://github.com/paulo-coutinho/pdfium-lib/issues/33.

We need upstream input, awareness/acknowledgement of the issue and hope it is addressed / fixed upstream.

Calling Bitmap_Destroy(Bitmap_Create*(495, 495, 4)) ✔️ is ok; Bitmap_Destroy(Bitmap_Create*(496, 496, 4)) ❌ starts leaking.
```

**Comment by paulo-coutinho** [comment]
Wow. Im writing a message now with the link to this issue. More 10 seconds and we post twice rsrsrsrsrs.

Thanks.

**Comment by cetinsert** [comment]
I just checked out `4542` hoping I can build it in a simple manner but then https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#System-requirements hit me! I have everything except disk space (I have that too but in WSL-2 via Windows, which will be slow for builds but at least I can finally confirm what slowness everyone is talking about) and Tuesday morning patience/time for their build tools. I will revisit this later this week.

Have you ever made local C/C++ builds of PDFium?

> Wow. Im writing a message now with the link to this issue. More 10 seconds and we post twice rsrsrsrsrs.

I really hope our posts to upstream pdfium gets noticed and acted on.

> Thanks.

I do thank *you* too for making PDFium accessible to everyone on the web.

**Comment by cetinsert** [comment]
https://groups.google.com/g/pdfium/c/9nwjxUGUaQs

> If you think you found a bug in PDFium, then please file a bug report
on https://crbug.com/pdfium. If possible, include a sample C/C++
program to demonstrate the issue.

**Comment by cetinsert** [comment]
https://bugs.chromium.org/p/pdfium/issues/detail?id=1692

**Comment by cetinsert** [comment]
(sorry I was trying to close the tab, not the issue o__O)

**Comment by paulo-coutinho** [comment]
Hi man.

I had a recent surgery and I'm in pain, so I can't always respond, but I saw what you did and I thank you for the excellent effort for the community.

I will wait they check your issue created.

**Comment by cetinsert** [comment]
@paulo-coutinho – I wish you a swift and complete recovery! Please do rest well.

I will do my best to follow up with upstream and keep you in the know.

**Comment by cetinsert** [comment]
Tested in C/C++. No leaks.

# steps

1. get https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-linux.tgz
2. extract into directory `TEST`
3. cd `TEST`
4. `export PDFium_DIR=$(pwd)`
5. `git clone https://github.com/bblanchon/pdfium-binaries.git`
6. `cd example`
7. `cmake .`
8. replace `example.c` with the code given below
9. `clear; rm example; make; ./example`
10. check memory usage with a tool like `htop` at each pause
11. no leaks ✔️

# `example.c`

```C
#include <fpdfview.h>
#include <stdio.h>

int main()
{
  printf("⌨ init ...\n");               /*getchar();*/                              FPDF_InitLibrary();
  printf("⌨ test 495  ×  495 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx( 495,  495, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ test 4096 × 4096 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx(4096, 4096, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ test 4096 × 4096 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx(4096, 4096, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ test 4096 × 4096 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx(4096, 4096, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ test 4096 × 4096 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx(4096, 4096, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ test 4096 × 4096 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx(4096, 4096, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ test 4096 × 4096 × 4 ...\n"); getchar(); for (int i = 0; i < 1000; i++) FPDFBitmap_Destroy(FPDFBitmap_CreateEx(4096, 4096, FPDFBitmap_BGRA, 0, 0));
  printf("⌨ destroy ...\n");              getchar();                                FPDF_DestroyLibrary();
  printf("⌨ exit ...\n");
	return 0;
}
```

---

This might be an issue only affecting WASM builds. As we have confirmed all is good in upstream and this is likely to be due to WASM build configuration / `emscripten`, we can now investigate this further at a very slow pace (days to weeks) prioritizing your recovery from the surgery above all.

**Comment by cetinsert** [comment]
One interesting find I have just made is as follows:

`496` × `596` × `4` ✔️

```js
_PDFium_Init(); var w = 496, h = 596; for (let i = 0; i < 10000; i++) FPDF.Bitmap_Destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ✔️
```

![image](https://user-images.githubusercontent.com/27027/122018507-e528ac00-cdfd-11eb-9352-2658c28384e6.png)

`496` × `496` × `4` ❌

```js
_PDFium_Init(); var w = 496, h = 496; for (let i = 0; i < 10000; i++) FPDF.Bitmap_Destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ❌
```

![image](https://user-images.githubusercontent.com/27027/122018366-bf9ba280-cdfd-11eb-9fd1-ea5bd9f01d19.png)

---

Perhaps a memory alignment bug of some sort in the WASM build or `emscripten` itself?

**Comment by cetinsert** [comment]
# Discovery 🕵🏻‍♂️

```js
_PDFium_Init(); var w = 496, h = 496; for (let i = 0; i < 100; i++) FPDF.Bitmap_Destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ❌
```
and the below are the same

```js
fpdf_bitmap_destroy = x => {};
_PDFium_Init(); var w = 496, h = 496; for (let i = 0; i < 100; i++) fpdf_bitmap_destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ❌
```

so it is not a partial leak as I first thought but a **complete failure**. **The whole memory block of the bitmap leaks.**

# References
`FPDFBitmap_Destroy()` – [chromium/4542/fpdfsdk/fpdf_view.cpp#884](https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4542/fpdfsdk/fpdf_view.cpp#884) is defined as

```cpp
FPDF_EXPORT void FPDF_CALLCONV FPDFBitmap_Destroy(FPDF_BITMAP bitmap) {
  RetainPtr<CFX_DIBitmap> destroyer;
  destroyer.Unleak(CFXDIBitmapFromFPDFBitmap(bitmap));
}
```

`RetainPtr<T>.Unleak()` – [chromium/4542/core/fxcrt/retain_ptr.h#62](https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4542/core/fxcrt/retain_ptr.h#62)
`CFXDIBitmapFromFPDFBitmap()` – [chromium/4542/fpdfsdk/cpdfsdk_helpers.h#78](https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4542/fpdfsdk/cpdfsdk_helpers.h#78)

# Thoughts

This might be related to
1. calling conventions
2. memory alignment
3. type cast failure in `CFXDIBitmapFromFPDFBitmap()`

Perhaps the issue is local to `FPDF.Bitmap_Destroy()` only because what `FPDF.Bitmap_CreateEx()` returns does behave as expected when probed with

```js
FPDF.Bitmap_GetWidth  = Module.cwrap('FPDFBitmap_GetWidth',  'number', ['number']);
FPDF.Bitmap_GetHeight = Module.cwrap('FPDFBitmap_GetHeight', 'number', ['number']);
```

**Comment by cetinsert** [comment]
# 🕵🏻‍♂️ Discovery

This is due to memory alignment!

```js
_PDFium_Init();
```

### `495` × `495` × `4` ✔️

```js
var w = 495, h = 495; for (let i = 0; i < 5; i++) _FPDFBitmap_Destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ✔️
```

In the good case, the `memalign` `memset` `free` calls happen only once!

```
  CreateEx
    memalign memset free
    memalign memset free
    memalign memset
  Destroy

  CreateEx
  Destroy

  CreateEx
  Destroy

  CreateEx
  Destroy

  CreateEx
  Destroy
```

### `496` × `496` × `4` ❌

In this case, they keep happening at each iteration!!

```js
var w = 496, h = 496; for (let i = 0; i < 5; i++) _FPDFBitmap_Destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ❌
```

```
  CreateEx
    memalign memset free
    memalign memset free
    memalign memset
  Destroy

  CreateEx
    memalign memset free
    memalign memset free
    memalign memset
  Destroy

  CreateEx
    memalign memset free
    memalign memset free
    memalign memset
  Destroy

  CreateEx
    memalign memset free
    memalign memset free
    memalign memset
  Destroy

  CreateEx
    memalign memset free
    memalign memset free
    memalign memset
  Destroy
```

**Comment by paulo-coutinho** [comment]
I have updated all to latest commit and updated emscripten to latest version too.

You can test here:
https://pdfviewer.github.io/

**Comment by cetinsert** [comment]
It still leaks:

![image](https://user-images.githubusercontent.com/27027/122157523-f0cfad80-cea5-11eb-9e58-eb07a8ad41ee.png)

as we can now reproduce it in a single line we should be in a position to try different compilation options rapidly. I bet there will be a flag or sth. that makes this just work. (I have not yet got to compile this with emscripten myself but will get to it within this week.)

**Comment by cetinsert** [comment]
We might need to check these eventually:
- https://emscripten.org/docs/debugging/Sanitizers.html
- https://emscripten.org/docs/porting/Debugging.html#debugging-safe-heap

**Comment by cetinsert** [comment]
@paulo-coutinho updated https://github.com/emscripten-core/emscripten/issues/14459 with all the details I can think of.

**Comment by cetinsert** [comment]
@paulo-coutinho – o__O I have made a very interesting discovery!

Run this once (does not leak):

```js
_PDFium_Init(); clear();
var A = 0, Z = 10, n = 1, DS = new Set(), DF = new Set();
for (let w = A; w < Z; w++)
for (let h = A; h < Z; h++) {
  const a = wasmMemory.buffer.byteLength;
  for (let i = 0; i < n; i++) _FPDFBitmap_Destroy(_FPDFBitmap_CreateEx(w, h, FPDF.Bitmap_BGR));
  const z = wasmMemory.buffer.byteLength;
  const s = a == z ? DS : DF; s.add({ w, h, '*': w * h, '+': w + h, d: z - a });
}
```

and this also no longer leaks memory o__O

```js
var w = 496, h = 496; for (let i = 0; i < 5; i++) _FPDFBitmap_Destroy(FPDF.Bitmap_CreateEx(w, h, 4)); [ wasmMemory, wasmMemory.buffer.byteLength ] // ✔️
```

Have not tested the resulting `Module` state in production with real-life workloads yet though. Also I have low-confidence in such magic.

**Comment by cetinsert** [comment]
> It is the same even if we tell `FPDF` to use an external buffer as in `FPDF.Bitmap_CreateEx(width, height, format, buffer, ⋯)`.

This turned out to be false. Using external memory is a valid workaround for `Bitmap_CreateEx` leaks

```js
_PDFium_Init(); clear();
var XM = 1, A = 496, Z = 497, n = 100, CF = FPDF.Bitmap_BGRA, CS = 4, DS = new Set(), DF = new Set();
for (let w = A; w < Z; w++)
for (let h = A; h < Z; h++) {
  const a = wasmMemory.buffer.byteLength; const H = XM ? _malloc(w * h * CS) : 0;
  for (let i = 0; i < n; i++) _FPDFBitmap_Destroy(_FPDFBitmap_CreateEx(w, h, CF, H, w * CS));
  const z = wasmMemory.buffer.byteLength; if (XM) _free(H);
  const s = a == z ? DS : DF; s.add({ w, h, '*': w * h, '+': w + h, d: z - a });
}; [ (Z - A) ** 2, DS.size, DF.size ]
```
- `XM` `=` `1` ✔️ (no leaks) (`_FPDFBitmap_Destroy` is not even necessary in this case.)
- `XM` `=` `0` ❌ (leaks)

---

But now, **`RenderPageBitmap` also leaks** with some files!

1. Watch `wasmMemory.buffer.byteLength / 1024 / 1024`
2. Open https://pdf.ist/r/1635.pdf
3. Render page no 1 repeatedly ...

(same issue, again due to `memalign` `⋯` , this time no obvious workaround)

**Comment by cetinsert** [comment]
# `RenderPageBitmap`

Additional insight was gained after following https://github.com/emscripten-core/emscripten/issues/14459#issuecomment-863392152 in https://github.com/emscripten-core/emscripten/issues/14459#issuecomment-863567813.

```js
(() => {
  const ins = (f, n) => (...a) => { const v = f(...a); console.warn(n, f, v, '<-', a); return v; };
  const { malloc, memalign, memset, free, realloc } = Module.asm;
  Module.asm = { ...Module.asm,
    malloc:   ins(malloc,   'malloc  '),
    memalign: ins(memalign, 'memalign'),
    memset:   ins(memset,   'memset  '),
    free:     ins(free,     'free    '),
    realloc:  ins(realloc,  'realloc ')
  };
})();
```

https://pdf.ist/r/1344.pdf

| 📄 `1` | 📄 `2` |
|-|-|
| ![image](https://user-images.githubusercontent.com/27027/122476328-f42b7c00-d000-11eb-8b1c-189ba77bac12.png) | ![image](https://user-images.githubusercontent.com/27027/122476409-1624fe80-d001-11eb-803c-da4963bbd35c.png) |
| no image | embedded image |

Repeatedly rendering the above pages result in exactly the same number of console entries from the instrumented functions.

**Comment by cetinsert** [comment]
### References

#### `memalign`

- https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4543/third_party/base/memory/aligned_memory.cc#30
- https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4543/third_party/libopenjpeg20/0034-opj_malloc.patch#26
- https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4543/third_party/libopenjpeg20/0034-opj_malloc.patch#34
- https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4543/third_party/libopenjpeg20/opj_malloc.cc#21
- https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/4543/third_party/libopenjpeg20/opj_malloc.cc#29

**Comment by cetinsert** [comment]
# `RenderPageBitmap` leaks

**Instrumentation** (improved from https://github.com/paulo-coutinho/pdfium-lib/issues/33#issuecomment-863587472)

```js
(() => {

  M = new Map();
  M.sum = () => [...M.values()].reduce((a, c) => a + c, 0);
  M.cnt = { malloc: 0, free: 0, sum: 0 };
  M.fn  = { malloc: 0, memalign: 1 };
  M.add = (n, a) => { M.   set(a, n); M.cnt.malloc++; M.cnt.sum += n; };
  M.sub =     a  => { M.delete(a   ); M.cnt.free++;                   };

  const ins = (f, n) => (...a) => {
    const v =  f(...a), d = a[M.fn[n]] ?? 0;
    if (d   >      0) M.add(d, v);
    if (n === 'free') M.sub(a[0]);
    console.warn(n.padEnd(8), f, `${v}`.padStart(20), '<-', (a.length == 1 ? [...a, '-'] : a).map(a => `${a}`.padStart(20)).join(' '), '|', `${M.sum()}`.padStart(20), 'M', M.size); return v;
  };

  const { malloc, memalign, memset, free, realloc } = Module.asm;
  Module.asm = { ...Module.asm,
    malloc:   ins(malloc,   'malloc'),
    memalign: ins(memalign, 'memalign'/*.length == 8*/),
  //memset:   ins(memset,   'memset'),
    free:     ins(free,     'free'),
    realloc:  ins(realloc,  'realloc')
  };

})();
```

| 📄 `1` ✔️ | 📄 `2` ❌ |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/27027/122496068-1daace80-d026-11eb-8df4-12b4f8ef2065.png) | ![image](https://user-images.githubusercontent.com/27027/122496132-374c1600-d026-11eb-82c4-af9751fdc5ac.png) |


```
function                             return    arguments                                           total memory   L
=================      ====================    =========================================   ====================   =
malloc   ƒ 4497() {  }             16584728 <-                   16                    - |                   16 M 1
free     ƒ 4498() {  }            undefined <-             16584728                    - |                    0 M 0
```

where the last `L` column is for leaks = un-freed allocations.

**Comment by cetinsert** [comment]
https://manned.org/em++/664a9826

Manual page of `em++` reads for `-O3`,

```
       -O3    As -O2, plus dangerous optimizations that may break the generated
              code! This adds

              -s FORCE_ALIGNED_MEMORY=1 -s DOUBLE_MODE=0 -s PRECISE_I64_MATH=0
              --closure 1 --llvm-lto 1

              This is not recommended at all. A better idea is to try each of
              these separately on top of -O2 to see what works. See the wiki and
              src/settings.js (for the -s options) for more information.
```

whereas this project does build with `-O3` as seen here: https://github.com/paulo-coutinho/pdfium-lib/blob/c95bc4a72502251bd3ee770d57907812945c6a2d/modules/wasm.py#L677 and we are indeed memory alignment issues.

**Comment by cetinsert** [comment]
@paulo-coutinho – please note https://github.com/emscripten-core/emscripten/issues/14459#issuecomment-864373169

**Comment by cetinsert** [comment]
@paulo-coutinho – I hope your surgery went well and you are doing OK.

- I have discovered `PDFium` is doing partial `munmap`s in WASM: https://github.com/emscripten-core/emscripten/issues/14459#issuecomment-864373169
- `emscripten` devs chose to `abort` on such behavior in future releases: https://github.com/emscripten-core/emscripten/pull/14504#issuecomment-865648164
- I have discovered `PDFium` is not doing partial `munmap`s in Windows.
    - Lei Zhang from Google said imitating the Windows is worth a try https://groups.google.com/g/pdfium/c/cDkppTy9mEc/m/2V29h4t7AwAJ
      - I am trying to do so here: https://github.com/emscripten-core/emscripten/issues/14459#issuecomment-866066268
        - this seems to get ignored in my builds, even if I sprinkle `printf("test\n");` or `emscripten_force_exit(1);` in the modified `⋯_posix.h` file, these do not get executed.
        - so once you are back, please let me know here or on Twitter so that we can continue

**Comment by paulo-coutinho** [comment]
Hi man,

How are you? 

What is the conclusion about this problem? What do you think about this?

**Comment by cetinsert** [comment]
I am glad you're back! I will respond in detail later today.

**Comment by cetinsert** [comment]
@paulo-coutinho – sorry for the delay.

The latest on this is this comment: https://github.com/emscripten-core/emscripten/issues/14459#issuecomment-866900860 which we should follow up on.

**Comment by paulo-coutinho** [comment]
Updated:
https://pdfviewer.github.io/

Check releases.

**Comment by paulo-coutinho** [comment]
Hi,

I launched a new version (4692). 

To test, you can access:
https://pdfviewer.github.io/

Can you check the docs/code to see if your problem still happen?

You can donate, if you want, to help the project.

Thanks.

**Comment by paulo-coutinho** [comment]
Hi @cetinsert,

It still a problem? You think that a new version can fix it?

**Comment by cetinsert** [comment]
@paulo-coutinho – still a problem 😵,

1. navigate to https://pdfviewer.github.io/
2. do the 3 steps in this comment: https://github.com/paulo-coutinho/pdfium-lib/issues/33#issuecomment-861669272

![image](https://user-images.githubusercontent.com/27027/147643110-ce2490b3-d801-4a11-b9ac-d67bf368c2d7.png)

**Comment by paulocoutinhox** [comment]
Hi,

A new version was launched. Can you try?

Thanks.

**Comment by quincarter** [comment]
I will say that i have optimized this on a work project by only rendering a single page at a time and cleaning the memory heap after each page change. The wasm can handle it very well. I was using some older code but it was working nicely. My only thing i can't figure out now is how to render a PDF without this function: (which i mentioned in #71 )
```javascript
PDFium_GetRenderPageDataSize(doc, pageNumber);
```

**Comment by paulocoutinhox** [comment]
Hi,

If you know something about, share with us to we improve the project.

Thanks.

**Comment by quincarter** [comment]
After each page render, you don't need to keep the full heap I don't think. In this instance, since you are rendering it to the dom, it can be cleaned and you can adjust your memory to account for the current page (if you truly want a full grid of all the pages).

In my instance I'm only rendering a single page (with a page turner on the UI) and not passing all pages into the `pages[]`. But I am capturing the total pages and I adjust the index before entering the rendering functions and the heap is cleaned after each render.

**Comment by cetinsert** [comment]
> After each page render, you don't need to keep the full heap I don't think. In this instance, since you are rendering it to the dom, it can be cleaned and you can adjust your memory to account for the current page (if you truly want a full grid of all the pages).
> 
> In my instance I'm only rendering a single page (with a page turner on the UI) and not passing all pages into the `pages[]`. But I am capturing the total pages and I adjust the index before entering the rendering functions and the heap is cleaned after each render. Again. This is on an older version using that custom function, but I have stress tested it with Apple's acknowledgements pdf for the ipod (262 pages) and it runs fine with no memory leak that I can see.

Memory leak only happens with certain files. Please try everything with https://pdf.ist/r/6365.pdf.

**Comment by cetinsert** [comment]
> Hi,
> 
> A new version was launched. Can you try?
> 
> Thanks.

Wow, I have just seen this. Trying now ...

**Comment by cetinsert** [comment]
1. Visit: https://pdfviewer.github.io/?title=RenderPageBitmap%20Leaks&url=https://pdf.ist/r/6365.pdf
2. Wait ...
3. Issue persists!
![image](https://user-images.githubusercontent.com/27027/170076556-7f0f1208-3ab9-432c-8a26-5df5429a458b.png)

**Comment by quincarter** [comment]
> We do that already. See: https://github.com/paulocoutinhox/pdfium-lib/issues/71#issuecomment-1136067094 – function H.

i recognize this now. It's making sense to me.

**Comment by paulocoutinhox** [comment]
Hi @cetinsert,

Do you think that put all steps "load, render, close and clear" inside one function (like @quincarter suggested) that is called every time that we want render a page, solve this problem? Instead of keep it initialized globally, we will call a function to render, wait for render response, and go to next after until finish, loading one page once until finish.

**Comment by cetinsert** [comment]
> Hi @cetinsert,
> 
> Do you think that put all steps "load, render, close and clear" inside one function (like @quincarter suggested) that is called every time that we want render a page, solve this problem? Instead of keep it initialized globally, we will call a function to render, wait for render response, and go to next after until finish, loading one page once until finish.

No. We do all that but still leak. Last time we talked to the `emscripten` guys, it looked a really fundamental problem that we can address at our end easily.

**Comment by quincarter** [comment]
This is all thread blocking btw. If i can get my solution working, i will contribute part of it to this repo as it removes a lot (if not all) of the thread blocking that happens in this index.html build. I have refactored a lot but its been difficult as the DOM manipulation has to be extracted to separate areas.

**Comment by paulocoutinhox** [comment]
Hi,

I tested with wasm version from a friend and the error persists:
https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F5092

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/395096/171338000-7d9c89d4-e593-432c-a448-c990889d18da.png">

Only to report that still need a solution.

**Comment by paulocoutinhox** [comment]
Hi,

All problems was fixed in new release.

You can check here:
https://github.com/paulocoutinhox/pdfium-lib/releases/tag/5407

The demo is here:
https://pdfviewer.github.io/

Feel free to donate to help project development.

Thanks.

**Comment by paulocoutinhox** [comment]
@CetinSert can i use this PDF for the iOS/Mac sample apps?

**Comment by quincarter** [comment]
Thanks for taking that on @paulocoutinhox - I got super busy and wasn't able to take up the open source projects I wanted to contribute to. I'll pull this and try it out!

**Comment by paulocoutinhox** [comment]
No problem,

Everything is working and done on master.

Feel free to donate to help project development.

**Comment by CetinSert** [comment]
> @CetinSert can i use this PDF for the iOS/Mac sample apps?

[https://pdf.ist/r/6365.pdf](https://pdfviewer.github.io/?title=RenderPageBitmap%20Leaks&url=https://pdf.ist/r/6365.pdf)? Yes, @paulocoutinhox, feel free to use any and all PDFs I have linked to in your examples. You can assume I will keep the `pdf.ist` domain for years to come. You can also make local copies as far as I am concerned. It is great to hear all issues have now been resolved. I have been waiting for this and more forms work from `PDF.js`, I will try updating WebPDF.pro and making it more accessible by making licensing/cost adjustments.
