### ISSUE TITLE
The file does not display correctly

### ISSUE THREAD

**Issue by none18l** [paulocoutinhox/pdfium-lib#48]
hi，The  below file does not display correctly in IPad,Do you konw the reason?
Thank you!

[1111.pdf](https://github.com/paulo-coutinho/pdfium-lib/files/7153228/1111.pdf)

**Comment by paulo-coutinho** [comment]
Hi,

Maybe problems with fonts:

![image](https://user-images.githubusercontent.com/395096/133171397-bc8c727b-3c9d-44d7-81b8-dee39c6ad796.png)

The fonts are embedded?

**Comment by cetinsert** [comment]
@paulo-coutinho – I have had the same experience with a Chinese-language PDF too. The font was supposed to be grabbed from the OS assuming a viewer with access to the fonts of the OS.

**Comment by paulo-coutinho** [comment]
@none18l do you have the fonts? 

@cetinsert in my local pdf reader on macOS it works, so based on your message it need work on browser too, no?

**Comment by cetinsert** [comment]
@paulo-coutinho 
I don't think PDFium bundles that many fonts. PDF spec mentions base 14 fonts. They would not have more in PDFium I believe. CJK fonts are larger in size and most likely not among the base 14. (There are also fonts with the same name that have fewer or more glyphs depending on how it's distributed.) Perhaps we can forward the issue to PDFium. Emscripten might provide a way to embed larger fonts in its emulated filesystem too.

**Comment by none18l** [comment]
No fonts.
but if PDFium  have  not  the fonts,how can I set the default font?

**Comment by paulo-coutinho** [comment]
I tested some pdfs with chinese fonts and it works:

![image](https://user-images.githubusercontent.com/395096/133473100-683f2eca-3177-4e09-82f7-749d31b7dc6d.png)
![image](https://user-images.githubusercontent.com/395096/133473175-d2d6de17-c709-4ac9-b0f4-f1b1802436c6.png)
[sample-ce-notice-chinese-trd.pdf](https://github.com/paulo-coutinho/pdfium-lib/files/7171848/sample-ce-notice-chinese-trd.pdf)
[Classical Chinese Sample 22208_0_8.pdf](https://github.com/paulo-coutinho/pdfium-lib/files/7171849/Classical.Chinese.Sample.22208_0_8.pdf)

**Comment by paulo-coutinho** [comment]
@none18l i recommend you read this:

https://www.eduhk.hk/ocio/content/faq-how-embed-asian-fonts-pdf-files
and
https://stackoverflow.com/questions/30083764/which-chinese-font-is-commonly-supported-by-pdf-readers-of-chinese-people

As i sad, you can embed fonts or it glyphs subset.

**Comment by cetinsert** [comment]
@paulo-coutinho – here is another file that does not render correctly that does not involve CJK fonts.

https://lab.webpdf.dev/#src=//try.httpfs.net/github.com/mozilla/pdf.js:/files/4652174/fff.pdf
[![image](https://user-images.githubusercontent.com/27027/133669651-358eb505-a4c6-4426-810b-a53324429ae9.png)](https://lab.webpdf.dev/#src=//try.httpfs.net/github.com/mozilla/pdf.js:/files/4652174/fff.pdf)

---

`🦊 PDF.js`' original issue which contains a recent fix: https://github.com/mozilla/pdf.js/issues/11915

**Comment by cetinsert** [comment]
@paulo-coutinho 

After reviewing the changes closing https://github.com/mozilla/pdf.js/issues/11915, I have come to the conclusion that they might be out of scope of this repository should they require source code changes in `PDFium` itself.

Embedding fonts via the emulated file system of `emscripten` (which I assume that it exists) would still be interesting to look at. Should that path ever be taken, the most flexible solution for the WASM port would be to expose adding such system fonts to the developer of websites themselves.

1. find out if the `PDFium` (original) checks a directory for system fonts
2. find out if `emscripten` provides a file system emulation API to users
3. document the directory (from 2) `PDFium` checks for system fonts
4. find the `emscripten` file system API to add font files to the directory (from 3)

The above steps would ensure more cases just work and require no code changes in `PDFium` proper or the WASM port of it.

**Comment by paulo-coutinho** [comment]
Hi,

I will check it.

**Comment by cetinsert** [comment]
another no-fonts file

- https://lab.webpdf.dev/#src=//try.httpfs.net/github.com/mozilla/pdf.js:/files/1634833/E-WG18_105147.pdf<br><sub>🦊 https://github.com/mozilla/pdf.js/issues/9367</sub>

**Comment by paulo-coutinho** [comment]
There is anything that i can do from my side?

**Comment by paulo-coutinho** [comment]
Hi,

I launched a new version (4692). 

To test, you can access:
https://pdfviewer.github.io/

Can you check the docs/code to see if your problem still happen?

You can donate, if you want, to help the project.

Thanks.

**Comment by cetinsert** [comment]
No changes with `4692`
1. https://github.com/paulo-coutinho/pdfium-lib/issues/48#issue-994678409 → https://lab.webpdf.dev/#src=//github.com/paulo-coutinho/pdfium-lib/files/7153228/1111.pdf – same with `4692` ![image](https://user-images.githubusercontent.com/27027/140598556-91263aff-6ca7-4fc2-985f-724c4147a88b.png)
2. https://github.com/paulo-coutinho/pdfium-lib/issues/48#issuecomment-921164020 – same<br>![image](https://user-images.githubusercontent.com/27027/140598429-7d7f553b-b1c1-48a5-8ba5-414da2459829.png)
3. https://github.com/paulo-coutinho/pdfium-lib/issues/48#issuecomment-922068059 – same<br>![image](https://user-images.githubusercontent.com/27027/140598465-5b375297-4162-4caf-be1f-15513f869361.png)

---

The situation will only improve if we bundle `PDFium` `wasm` build with fonts. `PDF.js` does call such files broken and does not spend developer time on them though.

**Comment by paulo-coutinho** [comment]
Hi

I don't understand. How `PDF.js` get these files and show correctly?

Thanks.

**Comment by cetinsert** [comment]
@paulo-coutinho they bundle fonts: https://github.com/mozilla/pdf.js/tree/master/external/standard_fonts (funnily enough from `PDFium` upstream)

**Comment by cetinsert** [comment]
Also, they refer to some likely not included ones that browsers might make available: https://github.com/mozilla/pdf.js/blob/e4f97a2a911a538be094fda434a216454690ea04/src/core/standard_fonts.js#L147 (these are more likely to have CJK glyphs)

**Comment by KDr2** [comment]
Some PDF files need external fonts to render, and WASM in browsers doesn't have the ability to access native files. I have managed to produce a version which will fetch fonts via HTTP requests if necessary (i.e., use HTTP Resources instead of local file system), but I am not sure if my company would like to let me open the solution yet.

**Comment by paulo-coutinho** [comment]
@KDr2 feel free to create a PR with all patchs to make it work.
@cetinsert what you think? we need download all that fonts and embed? that fonts are free?

**Comment by cetinsert** [comment]
@KDr2 – please create a PR, you may omit the font files or commit them as empty (0-byte). Should a full PR be difficult, please provide guidance on the necessary adjustments we would have to replicate on our own.
We will independently confirm the licensing requirements.

**Comment by paulocoutinhox** [comment]
Hi,

All problems was fixed in new release.

You can check here:
https://github.com/paulocoutinhox/pdfium-lib/releases/tag/5407

The demo is here:
https://pdfviewer.github.io/

I don't know if it still relevant. If anyone have a solution, please reopen and/or send the way to fix this.

Feel free to donate to help project development.

Thanks.
