### ISSUE TITLE
PDFium crash on iOS

### ISSUE THREAD

**Issue by DenL1** [paulocoutinhox/pdfium-lib#63]
**Describe the bug**
At run-time the libpdfium crashes the app in the ByteString::ByteString(const std::ostringstream& outStream) constructor. 
This is due to foogle changing the build tools and incorrect config of 'use_custom_libcxx'=true when it must be false:
build/config/c++/c++.gni  FIX

  use_custom_libcxx =
      is_fuchsia || is_android || is_mac || is_linux || is_chromeos_lacros ||
      (is_win && is_clang) ||
      (is_chromeos && default_toolchain != "//build/toolchain/cros:target")

% diff -Nuar ./pdfium-lib.4895/build/ios/pdfium/build/config/c++/c++.gni ./pdfium-lib.4895/build/ios/pdfium.copy/build/config/c++/c++.gni

--- ./pdfium-lib.4895/build/ios/pdfium/build/config/c++/c++.gni	2022-03-01 15:58:17.000000000 -0800
+++ ./pdfium-lib.4895/build/ios/pdfium.copy/build/config/c++/c++.gni	2022-03-03 13:30:14.000000000 -0800
@@ -12,7 +12,7 @@
   # Don't check in changes that set this to false for more platforms; doing so
   # is not supported.
   use_custom_libcxx =
-      is_fuchsia || is_android || is_apple || is_linux || is_chromeos_lacros ||
+      is_fuchsia || is_android || is_mac || is_linux || is_chromeos_lacros ||
       (is_win && is_clang) ||
       (is_chromeos && default_toolchain != "//build/toolchain/cros:target")
 
(man the `patch` command)

**To Reproduce**
Should almost always happen if HexStrings are in the PDF.

2. Execute on terminal '....'
3. See error

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: iOS
 - Version 15
 - Target x64 arm64

**Additional context**

**Comment by paulo-coutinho** [comment]
Hi,

If i understand the property `use_custom_libcxx ` need be false only for iOS, is this?

Thanks.

**Comment by DenL1** [comment]
Hi Paulo,

Yes, it seems that it needs to be FALSE for now. 

The last working PDFium build (Chromium 4685, October 29 ’21) that would run iOS had this:

  # Use in-tree libc++ (buildtools/third_party/libc++ and
  # buildtools/third_party/libc++abi) instead of the system C++ library for C++
  # standard library support.
  # Don't check in changes that set this to false for more platforms; doing so
  # is not supported.
  use_custom_libcxx =
      is_fuchsia || is_android || is_mac || is_linux || is_chromeos_lacros ||
      (is_ios && !use_xcode_clang) || (is_win && is_clang) ||
      (is_chromeos && default_toolchain != "//build/toolchain/cros:target")

Which would evaluate FALSE.  They cut out  '(is_ios && !use_xcode_clang)' and changed ‘is_map' into ‘is_apple' (is_apple = is_ios || is_mac).

A c++ constructor was getting corrupted values from ‘outStream’ in the ‘ByteString.cpp’ file: 
ByteString::ByteString(const std::ostringstream& outStream) {

I didn’t root cause why the third_party libc++ was doing this.  Switching back use_custom_libcxx to FALSE resolved the problem.  I did not test if problem is present on other platforms, just ios.

Dennis

**Comment by paulocoutinhox** [comment]
Ok, i will update the project and will fix it.

**Comment by paulocoutinhox** [comment]
Hi,

A new version was launched. Can you try?

Thanks.

**Comment by DenL1** [comment]
I tried it a second time, complete clean build, and it now works okay on the iOS device.  Something must of glitched on my first attempt.

Thanks
Dennis

**Comment by paulocoutinhox** [comment]
Nice. Is because of the new patches that i add in new version.

Feel free to donate to the project to help me!

Thanks.

**Comment by DenL1** [comment]
Hi Paulo,

I bought you a coffee.  
I did some exhaustive testing today.  And it seems that setting
”use_custom_libcxx=false”
In `ios.py` is not needed anymore and can work without the override.  

I tested use_custom_libcxx as both true and false and both modes function fine for PDFium branches: 
4938, 4844, 4896.

I’m not sure if google fixed something recently or I fixed something in my code.
(I’ll blame google).

So in your next release it should be fine to revert and remove the above args override.

Thanks
Dennis

**Comment by paulocoutinhox** [comment]
Hi,

I think that keep non custom libcxx is more "secure" and keep it updated to compiler libcxx, no?

The option `use_custom_libcxx=false` is already used in other platforms too, including `macos`, so, do you think that keep this option as `false` is bad? 

Thanks.

**Comment by DenL1** [comment]
It crashed on my iOS device (iPhone SE 2nd gen).  But, it did run okay on the simulator.
