### ISSUE TITLE
When trying to update to last versions of iOS builds the library is crashing a lots

### ISSUE THREAD

**Issue by zocario** [paulocoutinhox/pdfium-lib#65]
**Describe the bug**
We are using this library in our application to display vectorial PDFs in an iOS application. We've started with the first version of your builds and I tried to update to the latest released version. After updating to v4795 I'm having a lots of crashes when calling `FPDF_LoadPage` or `FPDF_RenderPageBitmap` on multiple threads.

**To Reproduce**
On our iOS implementation, if I open a big PDF File on thread A and start the rendering, then open an other file on thread B and start rendering while rendering of the first PDF is still occurring the library crashes.

It wasn't the case before so I'm wondering if there is anything that has changed in the way PDFium is compiled regarding multithreading? 

**Expected behavior**
The library doesn't crash when trying to render two files on separated threads.

**Screenshots**
No screenshots.

**System (please complete the following information):**
 - OS: iOS 15
 - Version v4795
 - Target iOS

**Additional context**
If you think it is relevant I could see if I can't create a sample showing the crash, but the code is very close to what was done on this project: https://github.com/baupen/SimplePDFKit.

I also tried to use the latest pdfium version (4915) with your script to see if it changes anything with the crashes but it was still the same.

**Comment by zocario** [comment]
I forgot to thank you for your work, which is super helpful for us 🙇‍♂️

**Comment by paulocoutinhox** [comment]
Hi,

A new version was launched. Can you try?

Thanks.

**Comment by zocario** [comment]
Thanks @paulocoutinhox I'll try it as soon as I have time to test it 🙏

**Comment by paulocoutinhox** [comment]
Nice,

Feel free to collab with donations if you want.

Thanks.

**Comment by zocario** [comment]
Hello @paulocoutinhox I'm still having the issue with last version, I think it must be related to our code and some multi-threading issues. I'm closing the issue as I think it comes from our side. 

Thanks for your help.
