### ISSUE TITLE
Awesome project. Small question regarding automation

### ISSUE THREAD

**Issue by quincarter** [paulocoutinhox/pdfium-lib#70]
Just want to say this project is freaking awesome. Thanks for doing the emscripten builds to wasm. This is great. I am using this wasm build at work and extended this. My question for you is, can I somehow pull in the latest version of the binary you have without having to manually come out and check for the latest? It would really help my automation. 

I did notice that the latest version broke my current rendering, but i think i fixed it looking at your example. 

EDIT:
I guess also i could just try to run your docker steps in our pipeline and get the latest from google. But i don't think we can get the emscripten docker image in our jenkins pipeline.

**Comment by paulocoutinhox** [comment]
Hi, thanks for the feedback.

I don't understand exactly what you want/need, but you always can get the latest version from releases page.

What you need exactly.

**Comment by quincarter** [comment]
Nvm on the original issue. I'll open a separate one for something else related to the new code in the WASM.
