### ISSUE TITLE
Is it possible to reduce the binary size

### ISSUE THREAD

**Issue by bupojung** [paulocoutinhox/pdfium-lib#77]
We introduced pdfium to our project, mainly for previewing pdf files, but the size of this library exceeded expectations. So I want to know if it is possible to compile the minimum capability we need to reduce the size of the binary.
Or is there any compile optimization option that can be set, thus reducing the binary size？

**Comment by paulocoutinhox** [comment]
Hi,

I will refactor all and remake a lot of things in this project. And when i start it, i will change this too.

Im only finishing another open source project that is a requirement for me.

Stay tuned here and feel free to donate to help project development.

Also, if you are building for release, it is the most compact mode that i know.

Thanks.

**Comment by bupojung** [comment]
Hi, I am a novice in compiling pdfium, is there any introductory document to learn?

**Comment by paulocoutinhox** [comment]
Hi, i think that only have the Google documents:
https://pdfium.googlesource.com/pdfium/

**Comment by paulocoutinhox** [comment]
Hi,

All problems was fixed in new release.

You can check here:
https://github.com/paulocoutinhox/pdfium-lib/releases/tag/5407

The demo is here:
https://pdfviewer.github.io/

I will close it, but feel free to reopen if need more help.

Feel free to donate to help project development.

Thanks.

**Comment by paulocoutinhox** [comment]
I found these instructions from Google:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/395096/200660470-0dd3c226-0740-44de-b771-fd5c21b3552d.png">

https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#smaller-builds

Maybe help you. You can try and post here the results.
