### ISSUE TITLE
pdfium.js source and/or docs

### ISSUE THREAD

**Issue by gonandriy** [paulocoutinhox/pdfium-lib#94]
Hi, Paulo,

First of all I appreciate your great project!

In your sample https://pdfviewer.github.io/ you use a pdfium.js script, which does all interconnection with pdfium lib. It is obfuscated in your demo. And I don't see it's source code neither docs, so can't figure out how to use it and build my custom.

Can you please advice where is the pdfium.js source? 

The default build contains only ecmascripten generated generic JS.

Thanks in advance.

**Comment by paulocoutinhox** [comment]
Hi, Thanks.

You can get the release here:
https://github.com/paulocoutinhox/pdfium-lib/releases

Inside the compressed file "wasm.tgz" you will find a folder like this:

<img width="146" alt="image" src="https://github.com/paulocoutinhox/pdfium-lib/assets/395096/e57e1116-f838-461a-a914-d963fc5e12ff">

The .JS file is generated from emscripten.

**Comment by gonandriy** [comment]
Hi, Paulo,
Thank you for you quick response.
Can you please advice what about wasm? It must be generated from another *.cpp source than the once in your sample.
And with a specific set of emscripten parameters.
Or Am I wrong?

Appreciate again you great project and kind help!

Regards,
Andrew.

**Comment by gonandriy** [comment]
Hi, Paulo,
Thanks a lot!
